var books = [
    {
        title: 'В конце они оба умрут',
        authorName: 'Янагихара Х.',
        categoryId: 3,
        img: '',
        price: 1443,
    },
    {
        title: 'Назови меня своим именем',
        authorName: 'Тартт Д.',
        categoryId: 1,
        img: '',
        price: 1200,
    },
    {
        title: 'Плененный принц',
        authorName: 'Сэнсом К.',
        categoryId: 2,
        img: '',
        price: 1500,
    },
    {
        title: 'Мара и Морок',
        authorName: 'Гэлбрейт Р.',
        categoryId: 1,
        img: '',
        price: 4000,
    },
    {
        title: 'Что, если это мы',
        authorName: 'Горовиц Э.',
        categoryId: 1,
        img: '',
        price: 2300,
    },
    {
        title: 'Королевство шипов и роз',
        authorName: 'Мосян Тунсю',
        categoryId: 1,
        img: '',
        price: 1200,
    },
    {
        title: 'Шестерка вороновлобок',
        authorName: 'Сакавич Н.',
        categoryId: 4,
        img: '',
        price: 10000,
    },
    {
        title: 'Ведьмак',
        authorName: 'Сапковский А.',
        categoryId: 2,
        img: '',
        price: 500,
    },
    {
        title: 'Приключения Крекера',
        authorName: 'Бардуго Л.',
        categoryId: 2,
        img: '',
        price: 1300,
    },
    {
        title: 'Мертвая земля: роман',
        authorName: 'Бардуго Л.',
        categoryId: 2,
        img: '',
        price: 450,
    },
]