var books = [
    {
        title: 'Русский яз.',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 1443,
    },
    {
        title: 'МЦЫРИ',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 1200,
    },
    {
        title: 'Му-Му',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 1500,
    },
    {
        title: 'Война и мир',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 4000,
    },
    {
        title: 'Вий',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 2300,
    },
    {
        title: 'Мертвые души',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 1200,
    },
    {
        title: 'колобок',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 10000,
    },
    {
        title: 'керкеркерке',
        authorName: 'rvberberbrtb evbebv',
        categoryId: 1,
        img: '',
        price: 500,
    },
]